#!/usr/bin/env python3
# ============================================
# 🤖 BNN Script Generator
# ============================================
# Generates the 8 security scripts from section 2.2.
# Usage: python3 scripts/gen.py
# ============================================

import os
import stat

SCRIPT_DIR = "/home/bnn-core/bnn-code/scripts"
SCRIPTS = {}

# Common header for all scripts
SCRIPT_HEADER = '''#!/bin/bash
# ============================================
# 🔧 BNN Auto-Generated Script
# ============================================
# THIS FILE IS AUTO-GENERATED BY gen.py - DO NOT EDIT MANUALLY
# ============================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
Iptables="iptables"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

info()  {{ echo -e "${CYAN}🔷${NC} $1"; }}
ok()    {{ echo -e "${GREEN}✅${NC} $1"; }}
warn()  {{ echo -e "${YELLOW}⚠️${NC} $1"; }}
err()   {{ echo -e "${RED}❌${NC} $1"; }}
'''

# Common vulnerable ports definition
PORTS_DEF = '''# 5 vulnerable ports to block/monitor
VULN_PORTS=(23 2323 4840 9000 5000)
PORTS_DESC=(
    "Telnet (TCP/23)"
    "Huawei Telnet (TCP/2323)"
    "Huawei TR-069 (TCP/4840)"
    "Management (TCP/9000)"
    "SSH brute force (TCP/5000)"
)

# Log prefix
LOG_PREFIX="SEC-DROP"
'''

# Common root check
ROOT_CHECK = '''# Check if running as root
check_root() {{
    if [[ "$EUID" -ne 0 ]]; then
        warn "Not running as root - some operations will be limited"
        SKIP_ROOT=true
    else
        SKIP_ROOT=false
    fi
}
'''

# Common footers
COMMON_FOOTER = '''

ok "Script generation complete"
'''


def write_script(filename, content):
    """Write a script file with executable permissions."""
    filepath = os.path.join(SCRIPT_DIR, filename)
    with open(filepath, 'w') as f:
        f.write(content)
    os.chmod(filepath, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
    print(f"Generated: {filename}")


def generate_apply_router_security():
    """Generate apply_router_security.sh"""
    content = """#!/bin/bash
# ============================================
# 🛡️ BNN Router Security — Apply iptables Rules
# ============================================
# Blocks the 5 vulnerable ports via iptables (INPUT DROP + LOG).
# Usage: ./scripts/apply_router_security.sh
# ============================================

{script_header}

{ports_def}

{root_check}

# Check if iptables is available
check_iptables() {{
    if ! command -v "$Iptables" &>/dev/null; then
        if $SKIP_ROOT; then
            warn "iptables not found - install it first (run with sudo for full functionality)"
        else
            err "iptables not found. Install it first."
            exit 1
        fi
    fi
}}

# Check if running as root
check_root() {{
    if [[ "$EUID" -ne 0 ]]; then
        warn "Not running as root - iptables operations will be skipped"
        SKIP_ROOT=true
    else
        SKIP_ROOT=false
    fi
}}

main() {{
    check_root
    check_iptables

    if $SKIP_ROOT; then
        warn "Skipping iptables rules (not running as root)"
        ok "Limited mode: port status checks only"
        info "Use 'sudo $0' for full iptables functionality"
        echo ""
        ok "apply_router_security.sh completed (limited mode)"
        return 0
    fi

    info "BNN Router Security - Applying iptables rules for 5 vulnerable ports"
    info "Log prefix: ${LOG_PREFIX}-*"

    # First flush any existing rules
    flush_rules

    # Block each vulnerable port
    for port in "${VULN_PORTS[@]}"; do
        block_port "$port"
    done

    echo ""
    ok "All 5 vulnerable ports blocked via iptables INPUT DROP + LOG"
    info "Log entries will appear with prefix: ${LOG_PREFIX}-PORT-<port>"
    info "Use 'setup_security_logging.sh' to also install the watcher service"
}}

main "$@"
""".format(
        script_header=SCRIPT_HEADER,
        ports_def=PORTS_DEF,
        root_check=ROOT_CHECK
    )
    write_script("apply_router_security.sh", content)


def generate_setup_security_logging():
    """Generate setup_security_logging.sh"""
    content = """#!/bin/bash
# ============================================
# 🛡️ BNN Security Logging Setup
# ============================================
# Installs LOG rules (prefix SEC-DROP-*) + security-alert-watcher.service.
# Usage: ./scripts/setup_security_logging.sh
# ============================================

{script_header}

{ports_def}

{root_check}

SYSTEMD_DIR="/etc/systemd/system"
WATCHER_SERVICE="security-alert-watcher.service"

main() {{
    check_root
    check_iptables

    if $SKIP_ROOT; then
        warn "Skipping iptables LOG rules (not running as root)"
        ok "Limited mode: watcher service setup only"
        info "Use 'sudo $0' for full iptables LOG rules functionality"
        echo ""
        # Still install the watcher service even without root
        install_watcher_service
        echo ""
        ok "setup_security_logging.sh completed (limited mode)"
        return 0
    fi

    info "BNN Security Logging Setup"
    info "Log prefix: ${LOG_PREFIX}-*"

    install_iptables_rules
    echo ""

    install_watcher_service
    echo ""

    enable_service
    echo ""

    show_rules

    echo ""
    ok "Security logging setup complete!"
    info "LOG rules installed with prefix: ${LOG_PREFIX}-<port>"
    info "Watcher service: ${WATCHER_SERVICE} active"
    info "Use 'apply_router_security.sh' to block the 5 vulnerable ports"
}}

main "$@"
""".format(
        script_header=SCRIPT_HEADER,
        ports_def=PORTS_DEF,
        root_check=ROOT_CHECK
    )
    write_script("setup_security_logging.sh", content)


def generate_security_monitor():
    """Generate security_monitor.sh"""
    content = """#!/bin/bash
# ============================================
# 🔍 BNN Security Monitor — Periodic nmap/TCP Scans
# ============================================
# Performs periodic nmap/TCP scans with alerting on vulnerable port detection.
# Usage: ./scripts/security_monitor.sh [--interval SECONDS] [--once]
# ============================================

{script_header}

{ports_def}

{root_check}

DEFAULT_INTERVAL=900

main() {{
    check_root
    local interval="$DEFAULT_INTERVAL"
    local once=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --interval)
                interval="$2"
                shift 2
                ;;
            --once)
                once=true
                shift
                ;;
            --help|-h)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --interval SECONDS  Scan interval in seconds (default: ${DEFAULT_INTERVAL}, i.e. 15 min)"
                echo "  --once              Run a single scan and exit"
                echo "  --help              Show this help message"
                exit 0
                ;;
            *)
                err "Unknown option: $1"
                echo "Usage: $0 [OPTIONS]"
                exit 1
                ;;
        esac
    done

    if $once; then
        info "Running single security scan..."
        scan_all_ports
        exit $?
    fi

    info "Starting BNN Security Monitor (interval: ${interval}s / $(($interval / 60))m)"
    info "Press Ctrl+C to stop"

    while true; do
        scan_all_ports
        info "Waiting ${interval}s until next scan..."
        sleep "$interval"
    done
}}
""".format(
        script_header=SCRIPT_HEADER,
        ports_def=PORTS_DEF,
        root_check=ROOT_CHECK
    )
    write_script("security_monitor.sh", content)


def generate_router_security_daemon():
    """Generate router_security_daemon.sh"""
    content = """#!/bin/bash
# ============================================
# 🛡️ BNN Router Security Daemon
# ============================================
# Periodic security daemon for router monitoring and alert handling.
# Runs in background, watches for security events, and triggers remediation.
# Usage: ./scripts/router_security_daemon.sh [--start|--stop|--status]
# ============================================

{script_header}

{ports_def}

{root_check}

PID_FILE="/var/run/bnn-router-daemon.pid"
LOG_FILE="/var/log/bnn-router-security.log"

main() {{
    check_root

    case "${1:-status}" in
        --start|start)
            start_daemon
            ;;
        --stop|stop)
            stop_daemon
            ;;
        --status|status)
            status_daemon
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --start, start      Start the security daemon"
            echo "  --stop, stop        Stop the security daemon"
            echo "  --status, status    Check daemon status"
            echo "  --help, -h          Show this help message"
            ;;
        *)
            err "Unknown option: $1"
            echo "Usage: $0 [OPTIONS]"
            exit 1
            ;;
    esac
}}

start_daemon() {{
    if is_running; then
        warn "Daemon already running (PID: $(cat "$PID_FILE"))"
        exit 0
    fi

    if $SKIP_ROOT; then
        warn "Running daemon in limited mode (no iptables monitoring)"
        info "Start with sudo for full functionality"
    fi

    info "Starting BNN Router Security Daemon..."

    # Create log file if needed
    touch "$LOG_FILE" 2>/dev/null || true

    # Start daemon in background
    bash "$SCRIPT_DIR/security_monitor.sh" --interval 300 \\
        >> "$LOG_FILE" 2>&1 &

    local pid=$!
    echo "$pid" > "$PID_FILE"

    ok "Daemon started (PID: $pid)"
    info "Log file: $LOG_FILE"
    if $SKIP_ROOT; then
        info "Scan interval: 300s (5 minutes) - limited mode"
    fi
}}

is_running() {{
    if [[ -f "$PID_FILE" ]]; then
        local pid
        pid=$(cat "$PID_FILE" 2>/dev/null)
        if [[ -d "/proc/$pid" ]]; then
            return 0
        fi
    fi
    return 1
}}

stop_daemon() {{
    if ! is_running; then
        warn "Daemon not running"
        exit 0
    fi

    local pid
    pid=$(cat "$PID_FILE")
    info "Stopping BNN Router Security Daemon (PID: $pid)..."

    kill "$pid" 2>/dev/null || true
    rm -f "$PID_FILE"

    # Wait for process to stop
    local timeout=10
    while [[ $timeout -gt 0 ]]; do
        if ! is_running; then
            break
        fi
        sleep 0.5
        ((timeout--))
    done

    if is_running; then
        warn "Process still running, forcing kill..."
        kill -9 "$pid" 2>/dev/null || true
    fi

    ok "Daemon stopped"
}}
""".format(
        script_header=SCRIPT_HEADER,
        ports_def=PORTS_DEF,
        root_check=ROOT_CHECK
    )
    write_script("router_security_daemon.sh", content)


def generate_router_monitor():
    """Generate router_monitor.sh"""
    content = """#!/bin/bash
# ============================================
# 📊 BNN Router Monitor — Periodic Status Check
# ============================================
# Periodic router security status monitor with alerting.
# Usage: ./scripts/router_monitor.sh [--interval SECONDS] [--once]
# ============================================

{script_header}

{ports_def}

{root_check}

DEFAULT_INTERVAL=60

main() {{
    check_root
    local interval="$DEFAULT_INTERVAL"
    local once=false
    local block=false
    local unblock=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --interval)
                interval="$2"
                shift 2
                ;;
            --once)
                once=true
                shift
                ;;
            --block)
                block=true
                shift
                ;;
            --unblock)
                unblock=true
                shift
                ;;
            --help|-h)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --interval SECONDS  Check interval in seconds (default: ${DEFAULT_INTERVAL}s)"
                echo "  --once              Run once and exit"
                echo "  --block             Block all vulnerable ports"
                echo "  --unblock           Unblock all vulnerable ports"
                echo "  --help              Show this help message"
                exit 0
                ;;
            *)
                err "Unknown option: $1"
                echo "Usage: $0 [OPTIONS]"
                exit 1
                ;;
        esac
    done

    if $block; then
        block_all_ports
        exit 0
    fi

    if $unblock; then
        unblock_all_ports
        exit 0
    fi

    if $once; then
        info "Running router security status check..."
        show_status
        exit $?
    fi

    info "Starting BNN Router Monitor (interval: ${interval}s)"
    info "Press Ctrl+C to stop"

    while true; do
        show_status
        info "Waiting ${interval}s until next check..."
        sleep "$interval"
    done
}}

block_all_ports() {{
    info "Blocking all 5 vulnerable ports via iptables..."

    for port in "${VULN_PORTS[@]}"; do
        "$Iptables" -A INPUT -p tcp --dport "$port" -j DROP
        ok "Blocked TCP/${port}"
    done

    ok "All vulnerable ports blocked"
}}

unblock_all_ports() {{
    info "Unblocking all 5 vulnerable ports via iptables..."

    for port in "${VULN_PORTS[@]}"; do
        "$Iptables" -D INPUT -p tcp --dport "$port" -j DROP
        ok "Unblocked TCP/${port}"
    done

    ok "All vulnerable ports unblocked"
}}
""".format(
        script_header=SCRIPT_HEADER,
        ports_def=PORTS_DEF,
        root_check=ROOT_CHECK
    )
    write_script("router_monitor.sh", content)


def generate_remediate_huawei_router():
    """Generate remediate_huawei_router.sh"""
    content = """#!/bin/bash
# ============================================
# ♻️ BNN Huawei Router Remediation
# ============================================
# Remediation procedures for Huawei router vulnerabilities.
# Usage: ./scripts/remediate_huawei_router.sh [--auto] [--help]
# ============================================

{script_header}

{ports_def}

{root_check}

HUAWEI_PORTS=(23 2323 4840)

main() {{
    check_root

    if $SKIP_ROOT; then
        warn "Running in limited mode (not root) - some remediation features disabled"
        ok "Limited mode: password/firmware commands available, port blocking skipped"
    fi

    local auto_mode=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --auto|-a)
                auto_mode=true
                shift
                ;;
            --help|-h)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --auto, -a          Run full auto-remediation"
                echo "  --help, -h          Show this help message"
                ;;
            *)
                err "Unknown option: $1"
                echo "Usage: $0 [OPTIONS]"
                exit 1
                ;;
        esac
    done

    info "=== Huawei Router Remediation ==="

    # Always block vulnerable ports first (if root)
    if ! $SKIP_ROOT; then
        block_huawei_ports
        echo ""
    fi

    if $auto_mode; then
        info "Running full auto-remediation..."
        remove_malicious_tr069
        change_default_passwords
        ok "Auto-remediation complete"
    fi

    echo ""
    ok "Remediation steps ready - use specific flags for individual actions"
}}

block_huawei_ports() {{
    info "Blocking Huawei vulnerable ports via iptables..."

    for port in "${HUAWEI_PORTS[@]}"; do
        if "$Iptables" -C INPUT -p tcp --dport "$port" -j DROP 2>/dev/null; then
            ok "Port TCP/${port} already blocked"
        else
            "$Iptables" -A INPUT -p tcp --dport "$port" -j DROP
            ok "Blocked Huawei port TCP/${port}"
        fi
    done

    # Also log the blocks
    for port in "${HUAWEI_PORTS[@]}"; do
        "$Iptables" -A INPUT -p tcp --dport "$port" -m state --state NEW -j LOG \
            --log-prefix "${LOG_PREFIX}-HUAWEI-${port}" \
            --log-level 4
        ok "Added LOG rule for Huawei port TCP/${port}"
    }}
}}
""".format(
        script_header=SCRIPT_HEADER,
        ports_def=PORTS_DEF,
        root_check=ROOT_CHECK
    )
    write_script("remediate_huawei_router.sh", content)


def generate_router_recovery_procedure():
    """Generate router_recovery_procedure.sh"""
    content = """#!/bin/bash
# ============================================
# 🔄 BNN Router Recovery Procedure
# ============================================
# Recovery procedures for compromised/restored Huawei routers.
# Usage: ./scripts/router_recovery_procedure.sh [--auto] [--help]
# ============================================

{script_header}

{ports_def}

{root_check}

LEGITIMATE_SERVICES=(
    "22:SSH"
    "80:HTTP"
    "443:HTTPS"
)

main() {{
    check_root

    if $SKIP_ROOT; then
        warn "Not running as root - some operations will be limited"
    fi

    info "=== BNN Router Recovery Procedure ==="
    echo ""

    # Step 1: Verify vulnerable ports are blocked
    verify_ports_blocked
    echo ""

    # Step 2: Restore legitimate services
    restore_legitimate_services
    echo ""

    # Step 3: Validate router state
    validate_router_state
    echo ""

    # Step 4: Check for re-compromise
    check_recompromise
    echo ""

    # Step 5: Generate recovery report
    generate_report
    echo ""

    ok "Recovery procedure complete"
    info "Next steps:"
    info "  1. Review the recovery report"
    info "  2. Monitor with: ./scripts/security_monitor.sh --once"
    info "  3. Check alerts: ./scripts/router_security_daemon.sh --status"
}}

verify_ports_blocked() {{
    info "Verifying vulnerable ports are blocked..."

    local all_blocked=true
    for port in "${VULN_PORTS[@]}"; do
        if "$Iptables" -C INPUT -p tcp --dport "$port" -j DROP 2>/dev/null; then
            ok "Port TCP/${port}: BLOCKED"
        else
            warn "Port TCP/${port}: NOT blocked - re-applying rule"
            "$Iptables" -A INPUT -p tcp --dport "$port" -j DROP
            all_blocked=false
        fi
    done

    if $all_blocked; then
        ok "All vulnerable ports are confirmed blocked"
    else
        warn "Some ports could not be blocked"
    fi
}}

restore_legitimate_services() {{
    info "Restoring legitimate services..."

    for rule in "${LEGITIMATE_SERVICES[@]}"; do
        local port="${rule%%:*}"
        local name="${rule#*:}"

        if ! "$Iptables" -C INPUT -p tcp --dport "$port" -j ACCEPT 2>/dev/null; then
            "$Iptables" -A INPUT -p tcp --dport "$port" -j ACCEPT
            ok "Allowed ${name} (TCP/${port})"
        else
            ok "${name} (TCP/${port}) already allowed"
        fi
    done

    ok "Legitimate services restored"
}}

validate_router_state() {{
    info "Validating router security state..."

    if command -v "$Nmap" &>/dev/null; then
        scan_results=$("$Nmap" -p "23,2323,4840,9000,5000" -T4 -F localhost 2>/dev/null || true)
        info "Port scan results:"
        echo "$scan_results" | while IFS= read -r line; do
            echo "  $line"
        done
    else
        warn "nmap not available - skipping state validation scan"
    fi

    ok "Router state validation complete"
}}

check_recompromise() {{
    info "Checking for signs of re-compromise..."

    local alert_log="/var/log/bnn-security-alerts.log"

    if [[ -f "$alert_log" ]]; then
        local recent_alerts
        recent_alerts=$(tail -n 20 "$alert_log" 2>/dev/null || true)

        if echo "$recent_alerts" | grep -qi "PORT_OPEN|SEC-DROP"; then
            warn "Recent security alerts detected - possible re-compromise"
            echo "$recent_alerts"
        else
            ok "No recent security alerts - system appears clean"
        fi
    else
        warn "No alert log found at $alert_log"
        info "Run security_monitor.sh to generate alerts log"
    fi
}}

generate_report() {{
    local report_file="/tmp/bnn_recovery_report_{date_%Y%m%d_%H%M%S}.txt"

    info "Generating recovery report: $report_file"

    {{
        echo "=== BNN Router Recovery Report ==="
        echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo ""
        echo "Vulnerable Ports Status:"
        for port in "${VULN_PORTS[@]}"; do
            if "$Iptables" -C INPUT -p tcp --dport "$port" -j DROP 2>/dev/null; then
                echo "  TCP/${port}: BLOCKED"
            else
                echo "  TCP/${port}: OPEN (UNBLOCKED)"
            fi
        done
        echo ""
        echo "Legitimate Services Status:"
        for rule in "${LEGITIMATE_SERVICES[@]}"; do
            local port="${rule%%:*}"
            local name="${rule#*:}"
            if "$Iptables" -C INPUT -p tcp --dport "$port" -j ACCEPT 2>/dev/null; then
                echo "  TCP/${port} (${name}): ALLOWED"
            else
                echo "  TCP/${port} (${name}): NOT allowed"
            fi
        done
        echo ""
        echo "=== End of Report ==="
    }} > "$report_file"

    ok "Report saved to $report_file"
    echo ""
    info "Review the report and verify all settings are correct"
}}
""".format(
        script_header=SCRIPT_HEADER,
        ports_def=PORTS_DEF,
        root_check=ROOT_CHECK,
        date='%Y%m%d_%H%M%S'
    )
    write_script("router_recovery_procedure.sh", content)


def generate_periodic_security_scan():
    """Generate periodic_security_scan.sh"""
    content = """#!/bin/bash
# ============================================
# 📊 BNN Periodic Security Scan
# ============================================
# Scheduled scan producing the port report.
# Usage: ./scripts/periodic_security_scan.sh [--output FILE] [--once] [--help]
# ============================================

{script_header}

{ports_def}

{root_check}

main() {{
    check_root

    if $SKIP_ROOT; then
        warn "Running in limited mode (not root) - iptables checks skipped"
        info "Report will show port status without iptables protection"
    fi

    local output_file=""
    local once=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --output)
                output_file="$2"
                shift 2
                ;;
            --once)
                once=true
                shift
                ;;
            --help|-h)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --output FILE       Save report to specified file"
                echo "  --once              Run once and exit (default: continuous mode)"
                echo "  --help, -h          Show this help message"
                ;;
            *)
                err "Unknown option: $1"
                echo "Usage: $0 [OPTIONS]"
                exit 1
                ;;
        esac
    done

    if $once; then
        run_scan
    else
        # Continuous mode - run scan every 24 hours
        info "Starting BNN periodic security scan (continuous mode)"
        info "Scanning every 24 hours - press Ctrl+C to stop"

        while true; do
            run_scan
            info "Waiting 24h until next scan..."
            sleep 86400
        done
    fi
}}
""".format(
        script_header=SCRIPT_HEADER,
        ports_def=PORTS_DEF,
        root_check=ROOT_CHECK
    )
    write_script("periodic_security_scan.sh", content)


def main():
    """Generate all 8 security scripts"""
    print("=" * 60)
    print("BNN Script Generator - Section 2.2 Security Scripts")
    print("=" * 60)
    echo ""

    generate_apply_router_security()
    echo ""

    generate_setup_security_logging()
    echo ""

    generate_security_monitor()
    echo ""

    generate_router_security_daemon()
    echo ""

    generate_router_monitor()
    echo ""

    generate_remediate_huawei_router()
    echo ""

    generate_router_recovery_procedure()
    echo ""

    generate_periodic_security_scan()
    echo ""

    print("=" * 60)
    print("All 8 security scripts generated successfully!")
    print("=" * 60)


if __name__ == "__main__":
    main()